# Generated by Django 5.2.5 on 2025-08-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('signal', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('filledQTY', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('alert_chicago_time', models.DateTimeField()),
                ('secret', models.CharField(max_length=100)),
                ('wallet_balance', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('order_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
