# Generated by Django 5.2.5 on 2025-09-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAlertLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('alert_date_time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
    ]
